name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate release notes
        run: |
          echo "# Provisr ${{ github.ref_name }}" > ${{ github.workspace }}/RELEASE.md
          echo "" >> ${{ github.workspace }}/RELEASE.md
          git log --oneline --no-decorate $(git describe --tags --abbrev=0 HEAD^)..HEAD >> ${{ github.workspace }}/RELEASE.md
      - uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/RELEASE.md
          generate_release_notes: false